spring.application.name=x-rest

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

logging.level.org.springframework=DEBUG
logging.level.com.gestao_restaurante=DEBUG
