spring.application.name=x-rest

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://postgres.fnvagaofbemlokrgkxen:graduacao2025@aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fnvagaofbemlokrgkxen
spring.datasource.password=graduacao2025

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=NDAzRTYzNTI2NjU1NkE1ODZFMzcyMzU3NTM4NzhGMzEzRjQ0MkE0NzJEM0I2MTUwNjQ1M0c3VjZCNUI5MA==
application.security.jwt.expiration=86400000

logging.level.org.springframework=DEBUG
logging.level.com.gestao_restaurante=DEBUG