spring.application.name=x-rest

spring.datasource.url=jdbc:postgresql://db.fnvagaofbemlokrgkxen.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=zc4KXpjIt3MX3Nwd

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

application.security.jwt.secret-key=NDAzRTYzNTI2NjU1NkE1ODZFMzcyMzU3NTM4NzhGMzEzRjQ0MkE0NzJEM0I2MTUwNjQ1M0c3VjZCNUI5MA==
application.security.jwt.expiration=86400000