spring.application.name=campeao

# Supabase / Postgress
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.fnvagaofbemlokrgkxen.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=zc4KXpjIt3MX3Nwd

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=me

server.port=8081

# Chave base 64
jwt.secret=Q2hhdmVTZWNyZXRhU3VwZXJTZWd1cmExMjM0NTY3ODkw
jwt.expiration=120000

# spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console





